version: '20.10'

services: 
  mysqldb:
    image: mysql
    restart: always
    env_file: .env
    networks:
        - celtra_lotery_network
    environment:
      - MYSQL_ROOT_PASSWORD:$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE:$MYSQL_DATABASE
    ports:
      - $MYSQL_DOCKER_PORT:$MYSQL_DOCKER_PORT
    volumes: 
      - ./db:/docker-entrypoint-initdb.d
  app:
    networks:
        - celtra_lotery_network
    build:
      context: .
      dockerfile: ./scraper/Dockerfile
    image: scraper
    env_file: .env
    ports:
      - $NODEJS_DOCKER_PORT:$NODEJS_DOCKER_PORT
    volumes: 
      - ./scraper:/scraper
      - /scraper/node_modules
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true

volumes: 
  db-config:
  db-data:

networks:
  celtra_lotery_network: